### ISSUE TITLE
I got this after I login. Any fix?

### ISSUE THREAD

**Issue by CBBx218** [matricali/UBoat-Panel#4]
Warning: PDO::prepare(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'uboat.user' doesn't exist in /var/www/src/Model.php on line 42

Fatal error: Uncaught Error: Call to a member function execute() on boolean in /var/www/src/Model.php:46 Stack trace: #0 /var/www/src/models/user.php(11): Model->query('SELECT * FROM `...', Array) #1 /var/www/src/controllers/login.php(32): user->actionAuth(Array) #2 /var/www/src/goat.php(75): Login->index() #3 /var/www/html/index.php(22): goat->__construct(Array) #4 {main} thrown in /var/www/src/Model.php on line 46

**Comment by matricali** [comment]
You need to import the database structure into you MySQL/MariaDB
Look at https://github.com/UBoat-Botnet/UBoat-Panel/blob/master/uboat.sql
https://github.com/UBoat-Botnet/UBoat/wiki/Panel-Setup

**Comment by Jackson-Pollock** [comment]
Updated password column using 
```
MariaDB [uboat]> UPDATE user
                          -> SET password = 'new-pwdhash-here-using-test.php'
                          -> WHERE id = 1;
```
able to login thanks
