### ISSUE TITLE
Warning include

### ISSUE THREAD

**Issue by Zaiza777** [matricali/UBoat-Panel#5]
![image](https://user-images.githubusercontent.com/58741835/115601780-dbdfff00-a2e6-11eb-8c2e-935e30361eb0.png)
I wrote sudo docker-compose up --build
he gives me an answer like this 
But here we have not yet installed the database and have not done anything like this, we have done before
run phpmyadmin separately
Even in the database itself, a user was created, etc., but all the time the same error

**_I will be very glad for your help.=)_**

**Comment by matricali** [comment]
If you run the project using "docker-compose" you don't need to set up a separate database

**Comment by Zaiza777** [comment]
I tried to create on a clean system, but still the same error. Can we contact you by telegram? I can give you access to the server and check. It seems to me that I am doing something wrong. But we even completely reinstalled the server and tried to install via docker. The same problem

**Comment by Zaiza777** [comment]
???=p

**Comment by matricali** [comment]
> ???=p

What's your telegram ID?

**Comment by Zaiza777** [comment]
@saidikos
