### ISSUE TITLE
I can't get it to Install properly

### ISSUE THREAD

**Issue by PauloChoupinaIPB** [matricali/UBoat-Panel#6]
If I install via docker, i get this error: 

```
Warning: PDO::prepare(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'uboat.user' doesn't exist in /var/www/src/model.php on line 42

Fatal error: Uncaught Error: Call to a member function execute() on boolean in /var/www/src/model.php:46 Stack trace: #0 /var/www/src/models/user.php(11): Model->query('SELECT * FROM `...', Array) #1 /var/www/src/controllers/login.php(32): user->actionAuth(Array) #2 /var/www/src/goat.php(75): Login->index() #3 /var/www/html/index.php(22): goat->__construct(Array) #4 {main} thrown in /var/www/src/model.php on line 46

```

How can i install via docker and still manage to import de db?

Also if I just install lamp I try to install phpmyadmin via apt-get install phpmyadmin, I just get a blank page in the localhost/phpmyadmin

Also, if i just deploy a vps with wordpress, so that i can have lamp and phpmyadmin
I install and config but then no login page showing up.

IS THERE ANY WAY TO GET THIS RUNNNING?
that's my question!

**Comment by matricali** [comment]
Hi @PauloChoupinaIPB,

You need to import the schema into your database
See: https://github.com/UBoat-Botnet/UBoat/wiki/Panel-Setup
