### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by Victor725** [matricali/UBoat-Panel#7]
I've built the docker. When I log in with " username : root    password : root " , an error raised like this:

`Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/src/model.php:13 Stack trace: #0 /var/www/src/model.php(13): PDO->__construct('mysql:host=loca...', 'root', 'root') #1 /var/www/src/controller.php(25): Model->__construct() #2 /var/www/src/controllers/login.php(31): Controller->loadModel('user') #3 /var/www/src/goat.php(75): Login->index() #4 /var/www/html/index.php(22): goat->__construct(Array) #5 {main} thrown in /var/www/src/model.php on line 13`

**Comment by matricali** [comment]
If you aren't using the docker-compose service description provided then you need to change the database host in `src/config/config.php` accordingly

**Comment by Victor725** [comment]
OK, I'll try it.
Thanks very much!
